# Generated by Django 5.1.2 on 2024-10-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_questions_templeate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustn', models.CharField(max_length=122)),
                ('qustnId', models.CharField(max_length=122)),
                ('extra4', models.CharField(max_length=122)),
            ],
        ),
    ]
